package http

import (
	"net/http"

	"github.com/Sillyfrogster/Illarin/api/internal/api"
)

func registerRoutes(routes api.Routes, h *Handlers) {
	d := routes.Deadlines
	routes.Handle(http.MethodDelete, "/v1/notifications", d.JSON, h.ClearNotifications)
	routes.Handle(http.MethodGet, "/v1/notifications", d.JSON, h.ListNotifications)
	routes.Handle(http.MethodGet, "/v1/notifications/unread", d.JSON, h.CountUnreadNotifications)
	routes.Handle(http.MethodPost, "/v1/notifications/read", d.JSON, h.MarkAllNotificationsRead)
	routes.Handle(http.MethodDelete, "/v1/notifications/:id", d.JSON, h.RemoveNotification)
	routes.Handle(http.MethodPost, "/v1/notifications/:id/read", d.JSON, h.MarkNotificationRead)
	routes.Handle(http.MethodGet, "/v1/publication/categories", d.JSON, h.ListPublicationCategories)
	routes.Handle(http.MethodPut, "/v1/publication/categories", d.JSON, h.OrderPublicationCategories)
	routes.Handle(http.MethodPatch, "/v1/publication/categories/:id", d.JSON, h.UpdatePublicationCategory)
	routes.Handle(http.MethodGet, "/v1/publication/grants", d.JSON, h.ListPublicationGrants)
	routes.Handle(http.MethodPost, "/v1/publication/grants", d.JSON, h.CreatePublicationGrant)
	routes.Handle(http.MethodDelete, "/v1/publication/grants/:id", d.JSON, h.RevokePublicationGrant)
	routes.Handle(http.MethodPatch, "/v1/publication/grants/:id", d.JSON, h.UpdatePublicationGrant)
	routes.Handle(http.MethodGet, "/v1/publication/workspace", d.JSON, h.GetPublicationWorkspace)
	routes.Handle(http.MethodGet, "/v1/publication/posts", d.JSON, h.ListPosts)
	routes.Handle(http.MethodPost, "/v1/publication/posts", d.JSON, h.CreatePost)
	routes.Handle(http.MethodGet, "/v1/publication/posts/:id", d.JSON, h.GetPost)
	routes.Handle(http.MethodPut, "/v1/publication/posts/:id", d.JSON, h.SavePost)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/media", d.Upload, h.AddPostMedia)
	routes.Handle(http.MethodGet, "/v1/publication/posts/:id/revisions", d.JSON, h.ListPostRevisions)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/revisions", d.JSON, h.CheckpointPost)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/revisions/:revisionId/restore", d.JSON, h.RestorePostRevision)
	routes.Handle(http.MethodGet, "/v1/publication/posts/:id/history", d.JSON, h.ReadPostHistory)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/import", d.JSON, h.ImportPostMarkdown)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/publish", d.JSON, h.PublishPost)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/withdraw", d.JSON, h.WithdrawPost)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/republish", d.JSON, h.RepublishPost)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/delete", d.JSON, h.DeletePost)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/recover", d.JSON, h.RecoverPost)
	routes.Handle(http.MethodDelete, "/v1/publication/posts/:id/schedule", d.JSON, h.CancelPostSchedule)
	routes.Handle(http.MethodPost, "/v1/publication/posts/:id/schedule", d.JSON, h.SchedulePost)
	routes.Handle(http.MethodPut, "/v1/publication/posts/:id/schedule", d.JSON, h.ReplacePostSchedule)
	routes.Handle(http.MethodPut, "/v1/publication/posts/:id/address", d.JSON, h.CorrectPostAddress)
	routes.Handle(http.MethodPut, "/v1/publication/posts/:id/byline", d.JSON, h.CorrectPostByline)
	routes.Handle(http.MethodGet, "/v1/post-categories", d.JSON, h.ListPostCategories)
	routes.Handle(http.MethodGet, "/v1/post-apps", d.JSON, h.ListPostApps)
	routes.Handle(http.MethodGet, "/v1/posts", d.JSON, h.ListPublishedPosts)
	routes.Handle(http.MethodGet, "/v1/posts/:slug", d.JSON, h.GetPublishedPost)
	routes.Handle(http.MethodDelete, "/v1/profiles/:handle/restriction", d.JSON, h.RestoreProfile)
	routes.Handle(http.MethodGet, "/v1/profiles/:handle/restriction", d.JSON, h.GetProfileRestriction)
	routes.Handle(http.MethodPut, "/v1/profiles/:handle/restriction", d.JSON, h.RestrictProfile)
	routes.Handle(http.MethodGet, "/v1/assets/:id/preserved", d.JSON, h.ListPreservedNamespaces)
	routes.Handle(http.MethodDelete, "/v1/assets/:id/preserved/:namespace", d.JSON, h.DeletePreservedNamespace)
	routes.Handle(http.MethodDelete, "/v1/assets/:id/withhold", d.JSON, h.ClearAssetWithhold)
	routes.Handle(http.MethodPut, "/v1/assets/:id/withhold", d.JSON, h.WithholdAsset)
	routes.Handle(http.MethodGet, "/v1/assets/:id/media", d.JSON, h.ListMedia)
	routes.Handle(http.MethodPost, "/v1/assets/:id/media", d.Upload, h.AddMedia)
	routes.Handle(http.MethodGet, "/media/:media_id/:variant/:derivative_version", d.Download, h.GetMediaVariant)
}
