// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAccessToken struct {
	TokenHash      []byte
	ConnectedAppID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type AppLibraryEntry struct {
	ConnectedAppID      pgtype.UUID
	WorkID              pgtype.UUID
	VersionNumber       int32
	ReportedAt          pgtype.Timestamptz
	NotifiedTakenDownAt pgtype.Timestamptz
}

type AppRefreshHistory struct {
	TokenHash       []byte
	ConnectedAppID  pgtype.UUID
	RotatedAt       pgtype.Timestamptz
	DetectableUntil pgtype.Timestamptz
}

type Blob struct {
	ID         pgtype.UUID
	Sha256     []byte
	ByteSize   int64
	StorageKey string
}

type BlobCleanupMark struct {
	BlobID   pgtype.UUID
	MarkedAt pgtype.Timestamptz
}

type BlobTombstone struct {
	Sha256     []byte
	ReasonCode string
	PurgedAt   pgtype.Timestamptz
	ActorID    pgtype.UUID
}

type BlogActivityLog struct {
	ID            pgtype.UUID
	ActorID       pgtype.UUID
	Action        string
	CategoryID    pgtype.UUID
	SubjectID     pgtype.UUID
	RecordedAt    pgtype.Timestamptz
	Credential    string
	PostID        pgtype.UUID
	RevisionID    pgtype.UUID
	BeforeState   pgtype.Text
	AfterState    pgtype.Text
	ScheduleID    pgtype.UUID
	IntegrationID pgtype.UUID
	AttemptID     pgtype.UUID
}

type BlogCategory struct {
	ID        pgtype.UUID
	Slug      string
	Label     string
	Position  int32
	RetiredAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BlogDiscordRepair struct {
	ID              pgtype.UUID
	ActorID         pgtype.UUID
	AttemptID       pgtype.UUID
	TargetMessageID string
	Fingerprint     string
	Result          []byte
	CreatedAt       pgtype.Timestamptz
}

type BlogWriter struct {
	UserID     pgtype.UUID
	SwitchedBy pgtype.UUID
	Since      pgtype.Timestamptz
}

type ConnectedApp struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Name               string
	RefreshTokenPrefix string
	Permissions        []string
	ConnectedAt        pgtype.Timestamptz
	LastSeenAt         pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
	RefreshTokenHash   []byte
	AppName            string
	AppVersion         pgtype.Text
	ProtocolVersion    pgtype.Int4
	Capabilities       []string
	AcceptedFormats    []string
	LibraryAppVersion  pgtype.Text
}

type ConnectionAuthorization struct {
	RequestHash           []byte
	AuthorizationCodeHash []byte
	RedirectUri           string
	State                 string
	CodeChallenge         string
	AppName               string
	Name                  string
	AppVersion            pgtype.Text
	ProtocolVersion       int32
	Capabilities          []string
	AcceptedFormats       []string
	Permissions           []string
	ReviewedBy            pgtype.UUID
	ApprovedBy            pgtype.UUID
	ApprovedAt            pgtype.Timestamptz
	DeniedBy              pgtype.UUID
	DeniedAt              pgtype.Timestamptz
	RedeemedAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	UserCodeHash          []byte
}

type ConnectionRateLimit struct {
	KeyHash     []byte
	Action      string
	Attempts    int32
	WindowStart pgtype.Timestamptz
}

type ConnectionRequest struct {
	DeviceCodeHash      []byte
	UserCodeHash        []byte
	AppName             string
	Name                string
	AppVersion          pgtype.Text
	ProtocolVersion     int32
	Capabilities        []string
	AcceptedFormats     []string
	Permissions         []string
	ReviewTokenHash     []byte
	ReviewedBy          pgtype.UUID
	ApprovedBy          pgtype.UUID
	ApprovedAt          pgtype.Timestamptz
	DeniedBy            pgtype.UUID
	DeniedAt            pgtype.Timestamptz
	RedeemedAt          pgtype.Timestamptz
	LastPolledAt        pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	PollIntervalSeconds int32
}

type CreatorFollow struct {
	AccountID pgtype.UUID
	CreatorID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type DailyTotal struct {
	Day    pgtype.Date
	Kind   string
	WorkID pgtype.UUID
	Count  int32
}

type DiscordPost struct {
	ID        pgtype.UUID
	WebhookID pgtype.UUID
	Body      []byte
	Tries     int32
	DueAt     pgtype.Timestamptz
	SentAt    pgtype.Timestamptz
	FailedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type DiscordWebhook struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Address   []byte
	UpdatedAt pgtype.Timestamptz
}

type DownloadRecord struct {
	ID             int64
	WorkID         pgtype.UUID
	OriginalFileID pgtype.UUID
	Format         string
	HandedOffAt    pgtype.Timestamptz
	Access         string
	Visibility     string
}

type EmailVerificationToken struct {
	TokenHash []byte
	UserID    pgtype.UUID
	Email     string
	ExpiresAt pgtype.Timestamptz
}

type Event struct {
	Kind   string
	WorkID pgtype.UUID
	Day    pgtype.Date
}

type InboxEntry struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	Type        string
	WorkID      pgtype.UUID
	Words       []byte
	CreatedAt   pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
	UpdateCount int32
}

type MigrationException struct {
	ID         pgtype.UUID
	Type       string
	Subject    string
	Detail     string
	WorkID     pgtype.UUID
	RecordedAt pgtype.Timestamptz
}

type MigrationLegacyCounter struct {
	WorkID      pgtype.UUID
	V1Downloads int32
	V1Views     int32
	V1UpdatedAt pgtype.Timestamptz
	MigratedAt  pgtype.Timestamptz
}

type MigrationPreservedRecord struct {
	ID          pgtype.UUID
	SourceTable string
	SourceID    string
	WorkID      pgtype.UUID
	OwnerID     pgtype.UUID
	Payload     []byte
}

type MigrationStagedMedium struct {
	Source   string
	BlobID   pgtype.UUID
	Width    int32
	Height   int32
	StagedAt pgtype.Timestamptz
}

type Notification struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	Type        string
	WorkID      pgtype.UUID
	Words       []byte
	CreatedAt   pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
	UpdateCount int32
}

type NotificationEvent struct {
	ID         pgtype.UUID
	Type       string
	AccountID  pgtype.UUID
	WorkID     pgtype.UUID
	Words      []byte
	RecordedAt pgtype.Timestamptz
}

type OauthIdentity struct {
	UserID        pgtype.UUID
	Provider      string
	Subject       string
	ProviderEmail pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type OauthState struct {
	TokenHash      []byte
	Intent         string
	UserID         pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
	AppPreference  pgtype.Text
	NsfwPreference pgtype.Text
}

type PasswordResetToken struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type Post struct {
	ID               pgtype.UUID
	AuthorID         pgtype.UUID
	CategoryID       pgtype.UUID
	Status           string
	Slug             pgtype.Text
	Title            string
	Summary          string
	Body             []byte
	BodyVersion      int32
	WorkingVersion   int32
	PublishedAt      pgtype.Timestamptz
	UpdatedPublicAt  pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	PublicRevisionID pgtype.UUID
	HeaderMediaID    pgtype.UUID
	HeaderAlt        pgtype.Text
	HeaderCaption    pgtype.Text
	LinkCardMediaID  pgtype.UUID
	DeletedAt        pgtype.Timestamptz
	RecoverableUntil pgtype.Timestamptz
	DeletedBy        pgtype.UUID
}

type PostAddress struct {
	Slug        string
	CurrentSlug string
	Explanation string
	RetiredAt   pgtype.Timestamptz
}

type PostByline struct {
	PostID        pgtype.UUID
	AccountID     pgtype.UUID
	Handle        string
	DisplayName   string
	ContactEmail  string
	AvatarMediaID pgtype.UUID
	CapturedAt    pgtype.Timestamptz
}

type PostMediaUse struct {
	MediaID    pgtype.UUID
	PostID     pgtype.UUID
	RevisionID pgtype.UUID
}

type PostMedium struct {
	ID        pgtype.UUID
	PostID    pgtype.UUID
	BlobID    pgtype.UUID
	Purpose   string
	Width     int32
	Height    int32
	CreatedAt pgtype.Timestamptz
}

type PostRevision struct {
	ID              pgtype.UUID
	PostID          pgtype.UUID
	Number          int32
	Title           string
	Summary         string
	Slug            string
	CategoryID      pgtype.UUID
	Body            []byte
	BodyVersion     int32
	CapturedBy      pgtype.UUID
	CapturedAt      pgtype.Timestamptz
	HeaderMediaID   pgtype.UUID
	HeaderAlt       pgtype.Text
	HeaderCaption   pgtype.Text
	LinkCardMediaID pgtype.UUID
	CapturedFor     string
}

type PostSchedule struct {
	ID             pgtype.UUID
	PostID         pgtype.UUID
	RevisionID     pgtype.UUID
	DueAt          pgtype.Timestamptz
	State          string
	CreatedBy      pgtype.UUID
	Attempts       int32
	LeaseToken     pgtype.UUID
	LeaseExpiresAt pgtype.Timestamptz
	StoppedBecause pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	SettledAt      pgtype.Timestamptz
	Note           string
	PostToDiscord  bool
}

type PostSlug struct {
	Slug       string
	PostID     pgtype.UUID
	ReservedBy pgtype.UUID
	ReservedAt pgtype.Timestamptz
}

type PostUnpublishing struct {
	ID            pgtype.UUID
	PostID        pgtype.UUID
	RevisionID    pgtype.UUID
	Reason        string
	Explanation   string
	UnpublishedBy pgtype.UUID
	UnpublishedAt pgtype.Timestamptz
}

type PrivatePrompt struct {
	WorkID      pgtype.UUID
	OwnerType   string
	OwnerID     pgtype.UUID
	PayloadType string
	Payload     []byte
	SourceKey   pgtype.Text
	Digest      []byte
}

type PrivatePromptApp struct {
	WorkID pgtype.UUID
	App    string
}

type ProfileFeaturedWork struct {
	UserID   pgtype.UUID
	Position int32
	WorkID   pgtype.UUID
}

type ProfileMedium struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	BlobID    pgtype.UUID
	Width     int32
	Height    int32
	CreatedAt pgtype.Timestamptz
}

type PublicProfile struct {
	UserID        pgtype.UUID
	DisplayName   string
	Biography     string
	ContactEmail  string
	AvatarMediaID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	BannerMediaID pgtype.UUID
	BannerTint    pgtype.Text
}

type PublicProfileLink struct {
	UserID   pgtype.UUID
	Position int32
	Label    string
	Url      string
}

type RestrictedProfile struct {
	UserID       pgtype.UUID
	RestrictedBy pgtype.UUID
	Reason       string
	RestrictedAt pgtype.Timestamptz
}

type RestrictedProfileAudit struct {
	ID         pgtype.UUID
	ActorID    pgtype.UUID
	SubjectID  pgtype.UUID
	Action     string
	Reason     string
	RecordedAt pgtype.Timestamptz
}

type RetiredHandle struct {
	Handle string
}

type Send struct {
	ID             pgtype.UUID
	ConnectedAppID pgtype.UUID
	WorkID         pgtype.UUID
	State          string
	Attempts       int32
	QueuedAt       pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
	ChosenFormat   pgtype.Text
	SettledAt      pgtype.Timestamptz
	SettledReason  pgtype.Text
	ExpiresAt      pgtype.Timestamptz
	UpdatesInstall bool
}

type Session struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type UploadOperation struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	BlobID             pgtype.UUID
	Filename           string
	Status             string
	Name               pgtype.Text
	Blurb              pgtype.Text
	Tags               []string
	IsNsfw             pgtype.Bool
	Visibility         string
	WorkID             pgtype.UUID
	FailureReason      pgtype.Text
	Attempts           int32
	AvailableAt        pgtype.Timestamptz
	LeaseToken         pgtype.UUID
	LeaseExpiresAt     pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	TargetWorkID       pgtype.UUID
	FailureMessage     pgtype.Text
	CandidateVersion   pgtype.Int8
	ReplacementPreview []byte
}

type User struct {
	ID                             pgtype.UUID
	Username                       string
	Email                          pgtype.Text
	PasswordHash                   pgtype.Text
	EmailVerifiedAt                pgtype.Timestamptz
	EmailSource                    pgtype.Text
	CreatedAt                      pgtype.Timestamptz
	UpdatedAt                      pgtype.Timestamptz
	NsfwPreference                 string
	ShowNsfwContributionsOnProfile bool
	Role                           string
	DisplayName                    string
	CustomDisplayName              string
	AvatarUrl                      string
	BannerUrl                      string
	DefaultIncludeTags             []byte
	DefaultExcludeTags             []byte
	AppPreference                  pgtype.Text
}

type Work struct {
	ID                    pgtype.UUID
	Type                  string
	OriginalFileID        pgtype.UUID
	OwnerID               pgtype.UUID
	Name                  string
	Blurb                 string
	Tags                  []string
	CoverMediaID          pgtype.UUID
	IsNsfw                pgtype.Bool
	Visibility            string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	IndexedAt             pgtype.Timestamptz
	TakenDownAt           pgtype.Timestamptz
	TakenDownBy           pgtype.UUID
	TakenDownReason       pgtype.Text
	DeletedAt             pgtype.Timestamptz
	RecoverableUntil      pgtype.Timestamptz
	Lifecycle             string
	WorkVersion           string
	CreditedAuthor        string
	Nickname              string
	OriginalFormat        pgtype.Text
	PublishedVersionID    pgtype.UUID
	DraftedChangesVersion int64
}

type WorkBlock struct {
	ID         pgtype.UUID
	WorkID     pgtype.UUID
	Definition string
	Title      pgtype.Text
	Position   int32
	Hidden     bool
	Layout     string
	Width      string
	Elements   []byte
}

type WorkFollow struct {
	AccountID pgtype.UUID
	WorkID    pgtype.UUID
	State     string
	SetAt     pgtype.Timestamptz
}

type WorkFoundImage struct {
	ID        pgtype.UUID
	WorkID    pgtype.UUID
	MediaID   pgtype.UUID
	Address   string
	Name      string
	BlockID   pgtype.UUID
	Section   string
	Position  int32
	CreatedAt pgtype.Timestamptz
}

type WorkLegacyPath struct {
	Path      string
	WorkID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type WorkMedium struct {
	ID          pgtype.UUID
	WorkID      pgtype.UUID
	Role        string
	Width       pgtype.Int4
	Height      pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	BlobID      pgtype.UUID
	IsExtracted bool
	IsCurrent   bool
}

type WorkOriginalFile struct {
	ID         pgtype.UUID
	WorkID     pgtype.UUID
	Number     int32
	MediaType  string
	CreatedAt  pgtype.Timestamptz
	BlobID     pgtype.UUID
	Format     string
	Identifier string
}

type WorkPreservedDatum struct {
	ID        pgtype.UUID
	WorkID    pgtype.UUID
	OwnerType string
	OwnerID   pgtype.UUID
	Namespace string
	Payload   []byte
}

type WorkPublicPrivatePrompt struct {
	WorkID      pgtype.UUID
	OwnerType   string
	OwnerID     pgtype.UUID
	PayloadType string
	Payload     []byte
	SourceKey   pgtype.Text
	Digest      []byte
}

type WorkPublicWork struct {
	ID                 pgtype.UUID
	Type               string
	OriginalFileID     interface{}
	OwnerID            pgtype.UUID
	Name               interface{}
	Blurb              interface{}
	Tags               interface{}
	CoverMediaID       pgtype.UUID
	IsNsfw             bool
	Visibility         string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	IndexedAt          pgtype.Timestamptz
	TakenDownAt        pgtype.Timestamptz
	TakenDownBy        pgtype.UUID
	TakenDownReason    pgtype.Text
	DeletedAt          pgtype.Timestamptz
	RecoverableUntil   pgtype.Timestamptz
	Lifecycle          string
	WorkVersion        interface{}
	CreditedAuthor     interface{}
	Nickname           interface{}
	OriginalFormat     interface{}
	VersionNumber      pgtype.Int4
	PublishedVersionID pgtype.UUID
}

type WorkPublicWorkBlock struct {
	ID         pgtype.UUID
	WorkID     pgtype.UUID
	Definition string
	Title      pgtype.Text
	Position   int32
	Hidden     bool
	Layout     string
	Width      string
	Elements   []byte
}

type WorkPublicWorkMedium struct {
	ID          pgtype.UUID
	WorkID      pgtype.UUID
	Role        string
	Width       pgtype.Int4
	Height      pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	BlobID      pgtype.UUID
	IsExtracted bool
	IsCurrent   bool
}

type WorkPublicWorkPreservedDatum struct {
	ID        pgtype.UUID
	WorkID    pgtype.UUID
	OwnerType string
	OwnerID   pgtype.UUID
	Namespace string
	Payload   []byte
}

type WorkPublicWorkSummary struct {
	WorkID           pgtype.UUID
	Export           []byte
	ExportStamp      string
	ExportComputedAt pgtype.Timestamptz
	Facets           []byte
	FacetStamp       string
	FacetComputedAt  pgtype.Timestamptz
}

type WorkSummary struct {
	WorkID           pgtype.UUID
	Export           []byte
	ExportStamp      string
	ExportComputedAt pgtype.Timestamptz
	Facets           []byte
	FacetStamp       string
	FacetComputedAt  pgtype.Timestamptz
}

type WorkVersion struct {
	ID                    pgtype.UUID
	WorkID                pgtype.UUID
	Number                int32
	RecordedAt            pgtype.Timestamptz
	InitialRecorded       bool
	VersionLabel          string
	OriginalFileID        pgtype.UUID
	Payload               []byte
	PrivatePrompts        []byte
	Summary               string
	Notes                 string
	NotesEditedAt         pgtype.Timestamptz
	WithdrawnAt           pgtype.Timestamptz
	WithdrawalExplanation pgtype.Text
}

type WorkVersionMedium struct {
	VersionID pgtype.UUID
	WorkID    pgtype.UUID
	MediaID   pgtype.UUID
}

type WorkVersionPromptMatch struct {
	VersionID          pgtype.UUID
	CurrentFragmentID  pgtype.UUID
	RecordedFragmentID pgtype.UUID
	ResolvedAt         pgtype.Timestamptz
}

type WorkVersionSummary struct {
	VersionID pgtype.UUID
	Summary   []byte
}
