// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blob struct {
	ID         pgtype.UUID
	Sha256     []byte
	ByteSize   int64
	StorageKey string
}

type BlobSweepMark struct {
	BlobID   pgtype.UUID
	MarkedAt pgtype.Timestamptz
}

type BlobTombstone struct {
	Sha256     []byte
	ReasonCode string
	PurgedAt   pgtype.Timestamptz
	ActorID    pgtype.UUID
}

type DownloadEvent struct {
	ID                 int64
	WorkID             pgtype.UUID
	RevisionID         pgtype.UUID
	ExportTarget       string
	HandedOffAt        pgtype.Timestamptz
	AuthorizationClass string
	Visibility         string
}

type EmailVerificationToken struct {
	TokenHash []byte
	UserID    pgtype.UUID
	Email     string
	ExpiresAt pgtype.Timestamptz
}

type InboxEntry struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	Type        string
	WorkID      pgtype.UUID
	Words       []byte
	CreatedAt   pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
	UpdateCount int32
}

type IngestOperation struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	BlobID             pgtype.UUID
	Filename           string
	Status             string
	Name               pgtype.Text
	Blurb              pgtype.Text
	Tags               []string
	IsNsfw             pgtype.Bool
	Visibility         string
	WorkID             pgtype.UUID
	FailureReason      pgtype.Text
	Attempts           int32
	AvailableAt        pgtype.Timestamptz
	LeaseToken         pgtype.UUID
	LeaseExpiresAt     pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	TargetWorkID       pgtype.UUID
	FailureMessage     pgtype.Text
	CandidateVersion   pgtype.Int8
	ReplacementPreview []byte
}

type InstanceAccessToken struct {
	TokenHash  []byte
	InstanceID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type InstanceDelivery struct {
	ID             pgtype.UUID
	InstanceID     pgtype.UUID
	WorkID         pgtype.UUID
	State          string
	Attempts       int32
	QueuedAt       pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
	ChosenTarget   pgtype.Text
	SettledAt      pgtype.Timestamptz
	SettledReason  pgtype.Text
	ExpiresAt      pgtype.Timestamptz
	UpdatesInstall bool
}

type InstanceLibraryEntry struct {
	InstanceID         pgtype.UUID
	WorkID             pgtype.UUID
	ContentGeneration  int32
	ReportedAt         pgtype.Timestamptz
	NotifiedWithheldAt pgtype.Timestamptz
}

type InstanceRefreshHistory struct {
	TokenHash       []byte
	InstanceID      pgtype.UUID
	RotatedAt       pgtype.Timestamptz
	DetectableUntil pgtype.Timestamptz
}

type LinkAuthorization struct {
	RequestHash           []byte
	AuthorizationCodeHash []byte
	RedirectUri           string
	State                 string
	CodeChallenge         string
	ApplicationName       string
	InstanceName          string
	ApplicationVersion    pgtype.Text
	ProtocolVersion       int32
	Capabilities          []string
	AcceptedTargets       []string
	Scopes                []string
	ReviewedBy            pgtype.UUID
	ApprovedBy            pgtype.UUID
	ApprovedAt            pgtype.Timestamptz
	DeniedBy              pgtype.UUID
	DeniedAt              pgtype.Timestamptz
	RedeemedAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
}

type LinkRateLimit struct {
	KeyHash     []byte
	Action      string
	Attempts    int32
	WindowStart pgtype.Timestamptz
}

type LinkRequest struct {
	DeviceCodeHash      []byte
	UserCodeHash        []byte
	ApplicationName     string
	InstanceName        string
	ApplicationVersion  pgtype.Text
	ProtocolVersion     int32
	Capabilities        []string
	AcceptedTargets     []string
	Scopes              []string
	ReviewTokenHash     []byte
	ReviewedBy          pgtype.UUID
	ApprovedBy          pgtype.UUID
	ApprovedAt          pgtype.Timestamptz
	DeniedBy            pgtype.UUID
	DeniedAt            pgtype.Timestamptz
	RedeemedAt          pgtype.Timestamptz
	LastPolledAt        pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	PollIntervalSeconds int32
}

type LinkedInstance struct {
	ID                        pgtype.UUID
	UserID                    pgtype.UUID
	InstanceName              string
	RefreshTokenPrefix        string
	Scopes                    []string
	LinkedAt                  pgtype.Timestamptz
	LastSeenAt                pgtype.Timestamptz
	RevokedAt                 pgtype.Timestamptz
	RefreshTokenHash          []byte
	ApplicationName           string
	ApplicationVersion        pgtype.Text
	ProtocolVersion           pgtype.Int4
	Capabilities              []string
	AcceptedTargets           []string
	LibraryApplicationVersion pgtype.Text
}

type MigrationException struct {
	ID         pgtype.UUID
	Type       string
	Subject    string
	Detail     string
	WorkID     pgtype.UUID
	RecordedAt pgtype.Timestamptz
}

type MigrationLegacyCounter struct {
	WorkID      pgtype.UUID
	V1Downloads int32
	V1Views     int32
	V1UpdatedAt pgtype.Timestamptz
	MigratedAt  pgtype.Timestamptz
}

type MigrationPreservedRecord struct {
	ID          pgtype.UUID
	SourceTable string
	SourceID    string
	WorkID      pgtype.UUID
	OwnerID     pgtype.UUID
	Payload     []byte
}

type MigrationStagedMedium struct {
	Source   string
	BlobID   pgtype.UUID
	Width    int32
	Height   int32
	StagedAt pgtype.Timestamptz
}

type Notification struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	Type        string
	WorkID      pgtype.UUID
	Words       []byte
	CreatedAt   pgtype.Timestamptz
	ReadAt      pgtype.Timestamptz
	UpdateCount int32
}

type NotificationEvent struct {
	ID         pgtype.UUID
	Type       string
	AccountID  pgtype.UUID
	WorkID     pgtype.UUID
	Words      []byte
	RecordedAt pgtype.Timestamptz
}

type OauthIdentity struct {
	UserID        pgtype.UUID
	Provider      string
	Subject       string
	ProviderEmail pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type OauthState struct {
	TokenHash []byte
	Intent    string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type PasswordResetToken struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type Post struct {
	ID               pgtype.UUID
	AuthorID         pgtype.UUID
	GrantID          pgtype.UUID
	CategoryID       pgtype.UUID
	Status           string
	Slug             pgtype.Text
	Title            string
	Summary          string
	Document         []byte
	DocumentVersion  int32
	ReleaseAppID     pgtype.UUID
	ReleaseVersion   pgtype.Text
	ReleaseUrl       pgtype.Text
	WorkingVersion   int32
	PublishedAt      pgtype.Timestamptz
	UpdatedPublicAt  pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	PublicRevisionID pgtype.UUID
	HeaderMediaID    pgtype.UUID
	HeaderAlt        pgtype.Text
	HeaderCaption    pgtype.Text
	SocialMediaID    pgtype.UUID
	DeletedAt        pgtype.Timestamptz
	RecoverableUntil pgtype.Timestamptz
	DeletedBy        pgtype.UUID
}

type PostAddress struct {
	Slug        string
	CurrentSlug string
	Explanation string
	RetiredAt   pgtype.Timestamptz
}

type PostByline struct {
	PostID        pgtype.UUID
	AccountID     pgtype.UUID
	Handle        string
	DisplayName   string
	ContactEmail  string
	AvatarMediaID pgtype.UUID
	AppID         pgtype.UUID
	AppSlug       pgtype.Text
	AppName       pgtype.Text
	CapturedAt    pgtype.Timestamptz
}

type PostMediaUse struct {
	MediaID    pgtype.UUID
	PostID     pgtype.UUID
	RevisionID pgtype.UUID
}

type PostMedium struct {
	ID        pgtype.UUID
	PostID    pgtype.UUID
	BlobID    pgtype.UUID
	Purpose   string
	Width     int32
	Height    int32
	CreatedAt pgtype.Timestamptz
}

type PostRevision struct {
	ID              pgtype.UUID
	PostID          pgtype.UUID
	Number          int32
	Title           string
	Summary         string
	Slug            string
	CategoryID      pgtype.UUID
	Document        []byte
	DocumentVersion int32
	ReleaseAppID    pgtype.UUID
	ReleaseVersion  pgtype.Text
	ReleaseUrl      pgtype.Text
	CapturedBy      pgtype.UUID
	CapturedAt      pgtype.Timestamptz
	HeaderMediaID   pgtype.UUID
	HeaderAlt       pgtype.Text
	HeaderCaption   pgtype.Text
	SocialMediaID   pgtype.UUID
	CapturedFor     string
}

type PostSchedule struct {
	ID             pgtype.UUID
	PostID         pgtype.UUID
	RevisionID     pgtype.UUID
	DueAt          pgtype.Timestamptz
	State          string
	CreatedBy      pgtype.UUID
	Attempts       int32
	LeaseToken     pgtype.UUID
	LeaseExpiresAt pgtype.Timestamptz
	StoppedBecause pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	SettledAt      pgtype.Timestamptz
	Note           string
}

type PostScheduleDestination struct {
	ScheduleID    pgtype.UUID
	DestinationID pgtype.UUID
	MentionRole   bool
}

type PostSlug struct {
	Slug       string
	PostID     pgtype.UUID
	ReservedBy pgtype.UUID
	ReservedAt pgtype.Timestamptz
}

type PostWithdrawal struct {
	ID          pgtype.UUID
	PostID      pgtype.UUID
	RevisionID  pgtype.UUID
	Reason      string
	Explanation string
	WithdrawnBy pgtype.UUID
	WithdrawnAt pgtype.Timestamptz
}

type ProfileMedium struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	BlobID    pgtype.UUID
	Width     int32
	Height    int32
	CreatedAt pgtype.Timestamptz
}

type ProfileRestriction struct {
	UserID       pgtype.UUID
	RestrictedBy pgtype.UUID
	Reason       string
	RestrictedAt pgtype.Timestamptz
}

type ProfileRestrictionAudit struct {
	ID         pgtype.UUID
	ActorID    pgtype.UUID
	SubjectID  pgtype.UUID
	Action     string
	Reason     string
	RecordedAt pgtype.Timestamptz
}

type ProtectedContent struct {
	WorkID      pgtype.UUID
	OwnerType   string
	OwnerID     pgtype.UUID
	PayloadType string
	Payload     []byte
	SourceKey   pgtype.Text
	Digest      []byte
}

type ProtectedDeliveryApp struct {
	WorkID pgtype.UUID
	App    string
}

type PublicProfile struct {
	UserID        pgtype.UUID
	DisplayName   string
	Biography     string
	ContactEmail  string
	AvatarMediaID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type PublicProfileLink struct {
	UserID   pgtype.UUID
	Position int32
	Label    string
	Url      string
}

type PublicationApp struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	HomeUrl     string
	MarkMediaID pgtype.UUID
	Position    int32
	RetiredAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PublicationAppDestination struct {
	AppID         pgtype.UUID
	DestinationID pgtype.UUID
	ByDefault     bool
}

type PublicationAudit struct {
	ID            pgtype.UUID
	ActorID       pgtype.UUID
	Action        string
	AppID         pgtype.UUID
	CategoryID    pgtype.UUID
	GrantID       pgtype.UUID
	SubjectID     pgtype.UUID
	RecordedAt    pgtype.Timestamptz
	TokenID       pgtype.UUID
	Credential    string
	PostID        pgtype.UUID
	RevisionID    pgtype.UUID
	BeforeState   pgtype.Text
	AfterState    pgtype.Text
	ScheduleID    pgtype.UUID
	DestinationID pgtype.UUID
	DeliveryID    pgtype.UUID
}

type PublicationAuthority struct {
	UserID     pgtype.UUID
	AssignedAt pgtype.Timestamptz
}

type PublicationCategory struct {
	ID        pgtype.UUID
	Slug      string
	Label     string
	Position  int32
	RetiredAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PublicationDelivery struct {
	ID              pgtype.UUID
	EventID         pgtype.UUID
	DestinationID   pgtype.UUID
	DestinationName string
	State           string
	Attempts        int32
	LeaseToken      pgtype.UUID
	LeaseExpiresAt  pgtype.Timestamptz
	DueAt           pgtype.Timestamptz
	SettledAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Run             int32
	SettledReason   pgtype.Text
	MentionRole     bool
	MessageID       pgtype.Text
}

type PublicationDeliveryAttempt struct {
	ID          pgtype.UUID
	DeliveryID  pgtype.UUID
	Number      int32
	Outcome     string
	Status      pgtype.Int4
	Detail      string
	TookMs      int32
	AttemptedAt pgtype.Timestamptz
	Run         int32
}

type PublicationDestination struct {
	ID                  pgtype.UUID
	Type                string
	Name                string
	Host                string
	Address             []byte
	SigningSecret       []byte
	State               string
	VerifiedAt          pgtype.Timestamptz
	DisabledAt          pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Events              []string
	PreviousSecret      []byte
	PreviousSecretUntil pgtype.Timestamptz
	SigningSecretSetAt  pgtype.Timestamptz
	GuildID             pgtype.Text
	ChannelID           pgtype.Text
	WebhookName         pgtype.Text
	RoleID              pgtype.Text
	RoleName            pgtype.Text
}

type PublicationDiscordRepair struct {
	ID              pgtype.UUID
	ActorID         pgtype.UUID
	DeliveryID      pgtype.UUID
	TargetMessageID string
	Fingerprint     string
	Result          []byte
	CreatedAt       pgtype.Timestamptz
}

type PublicationEvent struct {
	ID         pgtype.UUID
	PostID     pgtype.UUID
	RevisionID pgtype.UUID
	Type       string
	OccurredAt pgtype.Timestamptz
	Note       string
}

type PublicationGrant struct {
	ID                     pgtype.UUID
	UserID                 pgtype.UUID
	AppID                  pgtype.UUID
	DefaultCategoryID      pgtype.UUID
	GrantedBy              pgtype.UUID
	GrantedAt              pgtype.Timestamptz
	RevokedAt              pgtype.Timestamptz
	Active                 bool
	DestinationsOverridden bool
}

type PublicationGrantCategory struct {
	GrantID    pgtype.UUID
	CategoryID pgtype.UUID
}

type PublicationGrantDestination struct {
	GrantID       pgtype.UUID
	DestinationID pgtype.UUID
	ByDefault     bool
}

type PublicationIdempotency struct {
	TokenID     pgtype.UUID
	Operation   string
	Key         string
	Fingerprint []byte
	Status      pgtype.Int4
	Response    []byte
	ClaimedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type PublicationMedium struct {
	ID        pgtype.UUID
	BlobID    pgtype.UUID
	Width     int32
	Height    int32
	CreatedAt pgtype.Timestamptz
}

type PublicationRateLimit struct {
	TokenID     pgtype.UUID
	Operation   string
	Attempts    int32
	WindowStart pgtype.Timestamptz
}

type PublicationToken struct {
	ID         pgtype.UUID
	GrantID    pgtype.UUID
	Name       string
	Prefix     string
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type RetiredHandle struct {
	Handle string
}

type Session struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID                             pgtype.UUID
	Username                       string
	Email                          pgtype.Text
	PasswordHash                   pgtype.Text
	EmailVerifiedAt                pgtype.Timestamptz
	EmailSource                    pgtype.Text
	CreatedAt                      pgtype.Timestamptz
	UpdatedAt                      pgtype.Timestamptz
	NsfwPreference                 string
	ShowNsfwContributionsOnProfile bool
	Role                           string
	DisplayName                    string
	CustomDisplayName              string
	AvatarUrl                      string
	BannerUrl                      string
	DefaultIncludeTags             []byte
	DefaultExcludeTags             []byte
}

type Work struct {
	ID                  pgtype.UUID
	Type                string
	CurrentRevisionID   pgtype.UUID
	OwnerID             pgtype.UUID
	Name                string
	Blurb               string
	Tags                []string
	CoverMediaID        pgtype.UUID
	IsNsfw              pgtype.Bool
	Visibility          string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	IndexedAt           pgtype.Timestamptz
	WithheldAt          pgtype.Timestamptz
	WithheldBy          pgtype.UUID
	WithheldReason      pgtype.Text
	DeletedAt           pgtype.Timestamptz
	RecoverableUntil    pgtype.Timestamptz
	Lifecycle           string
	WorkVersion         string
	CreditedAuthor      string
	Nickname            string
	OriginFormat        pgtype.Text
	ContentGeneration   int32
	PublishedSnapshotID pgtype.UUID
	WorkingCopyVersion  int64
}

type WorkBlock struct {
	ID         pgtype.UUID
	WorkID     pgtype.UUID
	Definition string
	Title      pgtype.Text
	Position   int32
	Hidden     bool
	Layout     string
	Width      string
	Elements   []byte
}

type WorkFollow struct {
	AccountID pgtype.UUID
	WorkID    pgtype.UUID
	State     string
	SetAt     pgtype.Timestamptz
}

type WorkLegacyPath struct {
	Path      string
	WorkID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type WorkMedium struct {
	ID          pgtype.UUID
	WorkID      pgtype.UUID
	Role        string
	Width       pgtype.Int4
	Height      pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	BlobID      pgtype.UUID
	IsExtracted bool
	IsCurrent   bool
}

type WorkPreservedDatum struct {
	ID        pgtype.UUID
	WorkID    pgtype.UUID
	OwnerType string
	OwnerID   pgtype.UUID
	Namespace string
	Payload   []byte
}

type WorkPublicProtectedContent struct {
	WorkID      pgtype.UUID
	OwnerType   string
	OwnerID     pgtype.UUID
	PayloadType string
	Payload     []byte
	SourceKey   pgtype.Text
	Digest      []byte
}

type WorkPublicWork struct {
	ID                  pgtype.UUID
	Type                string
	CurrentRevisionID   interface{}
	OwnerID             pgtype.UUID
	Name                interface{}
	Blurb               interface{}
	Tags                interface{}
	CoverMediaID        pgtype.UUID
	IsNsfw              bool
	Visibility          string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	IndexedAt           pgtype.Timestamptz
	WithheldAt          pgtype.Timestamptz
	WithheldBy          pgtype.UUID
	WithheldReason      pgtype.Text
	DeletedAt           pgtype.Timestamptz
	RecoverableUntil    pgtype.Timestamptz
	Lifecycle           string
	WorkVersion         interface{}
	CreditedAuthor      interface{}
	Nickname            interface{}
	OriginFormat        interface{}
	ContentGeneration   int32
	PublishedSnapshotID pgtype.UUID
}

type WorkPublicWorkBlock struct {
	ID         pgtype.UUID
	WorkID     pgtype.UUID
	Definition string
	Title      pgtype.Text
	Position   int32
	Hidden     bool
	Layout     string
	Width      string
	Elements   []byte
}

type WorkPublicWorkMedium struct {
	ID          pgtype.UUID
	WorkID      pgtype.UUID
	Role        string
	Width       pgtype.Int4
	Height      pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	BlobID      pgtype.UUID
	IsExtracted bool
	IsCurrent   bool
}

type WorkPublicWorkPreservedDatum struct {
	ID        pgtype.UUID
	WorkID    pgtype.UUID
	OwnerType string
	OwnerID   pgtype.UUID
	Namespace string
	Payload   []byte
}

type WorkPublicWorkSummary struct {
	WorkID           pgtype.UUID
	Export           []byte
	ExportStamp      string
	ExportComputedAt pgtype.Timestamptz
	Facets           []byte
	FacetStamp       string
	FacetComputedAt  pgtype.Timestamptz
}

type WorkRevision struct {
	ID         pgtype.UUID
	WorkID     pgtype.UUID
	Revision   int32
	MediaType  string
	CreatedAt  pgtype.Timestamptz
	BlobID     pgtype.UUID
	Format     string
	Identifier string
}

type WorkSnapshot struct {
	ID                    pgtype.UUID
	WorkID                pgtype.UUID
	Number                int32
	RecordedAt            pgtype.Timestamptz
	InitialRecorded       bool
	VersionLabel          string
	ContentGeneration     int32
	SourceRevisionID      pgtype.UUID
	Payload               []byte
	ProtectedPayloads     []byte
	Summary               string
	Notes                 string
	NotesEditedAt         pgtype.Timestamptz
	WithdrawnAt           pgtype.Timestamptz
	WithdrawalExplanation pgtype.Text
}

type WorkSnapshotMedium struct {
	SnapshotID pgtype.UUID
	WorkID     pgtype.UUID
	MediaID    pgtype.UUID
}

type WorkSnapshotPromptMatch struct {
	SnapshotID         pgtype.UUID
	CurrentFragmentID  pgtype.UUID
	RecordedFragmentID pgtype.UUID
	ResolvedAt         pgtype.Timestamptz
}

type WorkSnapshotSummary struct {
	SnapshotID pgtype.UUID
	Summary    []byte
}

type WorkSummary struct {
	WorkID           pgtype.UUID
	Export           []byte
	ExportStamp      string
	ExportComputedAt pgtype.Timestamptz
	Facets           []byte
	FacetStamp       string
	FacetComputedAt  pgtype.Timestamptz
}

type WorkUpdateDelivery struct {
	ID              pgtype.UUID
	EventID         pgtype.UUID
	DestinationID   pgtype.UUID
	DestinationName string
	DestinationType string
	State           string
	SettledReason   pgtype.Text
	MessageID       pgtype.Text
	Run             int32
	Attempts        int32
	LeaseToken      pgtype.UUID
	LeaseExpiresAt  pgtype.Timestamptz
	DueAt           pgtype.Timestamptz
	SettledAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type WorkUpdateDeliveryAttempt struct {
	ID          pgtype.UUID
	DeliveryID  pgtype.UUID
	Run         int32
	Number      int32
	Outcome     string
	Status      pgtype.Int4
	Detail      string
	TookMs      int32
	AttemptedAt pgtype.Timestamptz
}

type WorkUpdateDestination struct {
	ID                  pgtype.UUID
	OwnerID             pgtype.UUID
	Type                string
	Name                string
	Host                string
	Address             []byte
	SigningSecret       []byte
	SigningSecretSetAt  pgtype.Timestamptz
	PreviousSecret      []byte
	PreviousSecretUntil pgtype.Timestamptz
	GuildID             pgtype.Text
	ChannelID           pgtype.Text
	State               string
	VerifiedAt          pgtype.Timestamptz
	DisabledAt          pgtype.Timestamptz
	Version             int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type WorkUpdateDestinationDefault struct {
	WorkID        pgtype.UUID
	DestinationID pgtype.UUID
}

type WorkUpdateEvent struct {
	ID              pgtype.UUID
	WorkID          pgtype.UUID
	SnapshotID      pgtype.UUID
	Type            string
	OccurredAt      pgtype.Timestamptz
	UnlistedConsent bool
	Payload         []byte
}

type WorkVaultPicture struct {
	ID        pgtype.UUID
	WorkID    pgtype.UUID
	MediaID   pgtype.UUID
	Address   string
	Name      string
	BlockID   pgtype.UUID
	Section   string
	Position  int32
	CreatedAt pgtype.Timestamptz
}
